import { useState, useCallback, useEffect } from 'react';

import Head from 'next/head';
import { useRouter } from 'next/router';

import Grid from '@mui/material/Grid';
import Typography from '@mui/material/Typography';
import TextField from '@mui/material/TextField';
import Button from '@mui/material/Button';
import useMediaQuery from '@mui/material/useMediaQuery';
import { useTheme } from '@mui/material/styles';

import useUser from 'stores/User';
import LoadingModal from 'components/LoadingModal';

export default function LoginPage() {
   const theme = useTheme();
   const smQuery = useMediaQuery(theme.breakpoints.up('sm'));
   const router = useRouter();
   const {
      currentUser,
      status: userStatus,
      actions: { resetError, triggerLogin },
   } = useUser();

   const [ userName, setUserName ] = useState('');

   useEffect(() => {
      const redirectToHome = currentUser 
         && !userStatus.isLoading 
         && !userStatus.hasError;

      if (redirectToHome) {
         router.push('/');
      }
   }, [ router, currentUser, userStatus.isLoading, userStatus.hasError ]);

   const handleUserNameInput = (event) => {
      setUserName(event.target.value);
      
      if (userStatus.hasError) {
         resetError();
      }
   };

   const handleLogin = useCallback((event) => {
      event.preventDefault();
      triggerLogin(userName);
   }, [ userName, triggerLogin ]);

   return (
      <>
         <Head>
            <title>Aeolian | Log In</title>
            <meta name="description" content="Generated by create next app" />
         </Head>

         <LoadingModal isLoading={userStatus.isLoading} />

         <Grid
            container
            component="form"
            name="login"
            aria-live="polite"
            aria-busy={userStatus.isLoading}
            rowGap={3}
            direction="column"
            alignItems="center"
            justifyContent="center"
            sx={{
               minHeight: `calc(100vh - ${smQuery ? 64 : 56}px)`,
               width: {
                  xs: 280,
                  sm: 550,
                  md: 700,
               },
               margin: 'auto',
            }}
         >
            <Grid item xs={12}>
               <Typography variant="h3" component="h2">
                  Log In
               </Typography>
            </Grid>
            <Grid item xs={12}>
               <TextField
                  label="Username"
                  name="userName"
                  value={userName}
                  error={userStatus.hasError}
                  helperText={userStatus.hasError && 'Username invalid'}
                  onChange={handleUserNameInput}
                  sx={{ width: '25ch' }}
               />
            </Grid>
            <Grid item xs={12}>
               <Button
                  type="submit"
                  variant="outlined"
                  color={userStatus.hasError ? 'error' : 'primary'}
                  onClick={handleLogin}
               >
                  Submit
               </Button>
            </Grid>
         </Grid>
      </>
   );
}
