import Head from 'next/head';
import { useRouter } from 'next/router';
import Grid from '@mui/material/Grid';
import CircularProgress from '@mui/material/CircularProgress';
import useUser from 'utils/useUser';

export default function HomePage() {
   const router = useRouter();
   const [currentUser, userIsLoading, userHasError] = useUser();

   const showLoadingCircle = !currentUser && userIsLoading && !userHasError;
   const redirectToLogin = !currentUser && !userIsLoading && !userHasError;

   if (redirectToLogin) {
      router.push('/login');
   }

   return (
      <>
         <Head>
            <title>Aeolian | Air Quality Monitor</title>
            <meta name="description" content="Generated by create next app" />
         </Head>

         {showLoadingCircle ? (
            <Grid item>
               <CircularProgress size={150} />
            </Grid>
         ) : null}
      </>
   );

   // return (
   //    <div>
   //       <Head>
   //          <title>Aeolian | Air Quality Monitor</title>
   //          <meta name="description" content="Generated by create next app" />
   //       </Head>

   //       <main>
   //          <Grid
   //             container
   //             spacing={20}
   //             direction="column"
   //             alignItems="center"
   //             justify="center"
   //             sx={{ minHeight: '100vh', pt: 'calc(50vh - 75px)' }}
   //          >
   //             {showLoadingCircle && (
   //                <Grid item>
   //                   <CircularProgress size={150} />
   //                </Grid>
   //             )}
   //          </Grid>
   //       </main>
   //    </div>
   // );
}

// export async function getServerSideProps(context) {
//    try {
//       const { host } = context?.req.headers;
//       const res = await fetch({
//          url: `http://${host}/api/user`,
//          method: 'GET',
//          body: { userToken }
//       });
//       const json = await res.json();
//    } catch (error) {

//    }
// }
